// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type RepositoryOwner interface {
	IsRepositoryOwner()
}

type Organization struct {
	Login string `json:"login"`
}

func (Organization) IsRepositoryOwner() {}
