// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type RepositoryConfig struct {
	StartSchedule  string `json:"startSchedule"`
	StopSchedule   string `json:"stopSchedule"`
	MergeAvailable bool   `json:"mergeAvailable"`
}
