// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aereal/merge-chance-time/authflow (interfaces: GitHubAuthFlow)

// Package authflow is a generated GoMock package.
package authflow

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	url "net/url"
	reflect "reflect"
)

// MockGitHubAuthFlow is a mock of GitHubAuthFlow interface
type MockGitHubAuthFlow struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubAuthFlowMockRecorder
}

// MockGitHubAuthFlowMockRecorder is the mock recorder for MockGitHubAuthFlow
type MockGitHubAuthFlowMockRecorder struct {
	mock *MockGitHubAuthFlow
}

// NewMockGitHubAuthFlow creates a new mock instance
func NewMockGitHubAuthFlow(ctrl *gomock.Controller) *MockGitHubAuthFlow {
	mock := &MockGitHubAuthFlow{ctrl: ctrl}
	mock.recorder = &MockGitHubAuthFlowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubAuthFlow) EXPECT() *MockGitHubAuthFlowMockRecorder {
	return m.recorder
}

// NavigateAuthCompletion mocks base method
func (m *MockGitHubAuthFlow) NavigateAuthCompletion(arg0 context.Context, arg1, arg2 string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateAuthCompletion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateAuthCompletion indicates an expected call of NavigateAuthCompletion
func (mr *MockGitHubAuthFlowMockRecorder) NavigateAuthCompletion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateAuthCompletion", reflect.TypeOf((*MockGitHubAuthFlow)(nil).NavigateAuthCompletion), arg0, arg1, arg2)
}

// NewAuthorizeURL mocks base method
func (m *MockGitHubAuthFlow) NewAuthorizeURL(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAuthorizeURL", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAuthorizeURL indicates an expected call of NewAuthorizeURL
func (mr *MockGitHubAuthFlowMockRecorder) NewAuthorizeURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthorizeURL", reflect.TypeOf((*MockGitHubAuthFlow)(nil).NewAuthorizeURL), arg0, arg1, arg2)
}
